title: JS Star ë¸”ë¡œê·¸
description: js_star blog
author: JS Star ë¸”ë¡œê·¸
github: https://github.com/jsstar522
about: ê¸°ì–µë³´ë‹¤ëŠ” ê¸°ë¡ì„âœï¸ ë¨¸ì‹ ëŸ¬ë‹, ì›¹ê°œë°œ, ë¬¼ë¦¬í•™ì„ ê³µë¶€í–ˆê³  ê³„ì† ë°°ì›Œê°€ê³  ìˆìŠµë‹ˆë‹¤. <br> ğŸ“Œ ê¸°ì¡´ì— í¬ìŠ¤íŒ…í•˜ë˜ ë¸”ë¡œê·¸ì—ì„œ í¬ìŠ¤íŠ¸ë¥¼ ì˜®ê¸°ëŠ” ì¤‘ì…ë‹ˆë‹¤.
disqus_shortname: stackproblems
google_analytics: 

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/jsstar522"

share:
  twitter_username: 
  fb_appid: 1749788565247320

urls:
    - text: Post
      url: /
      children:
              - text: ë¨¸ì‹ ëŸ¬ë‹
                url: /category/machinelearning
              - text: GAN
                url: /category/gan
              - text: DATA MINING & ANALYSIS
                url: /category/analysis
              - text: KAGGLE
                url: /category/kaggle
              - text: <br>
              - text: ì•Œê³ ë¦¬ì¦˜
                url: /category/algorithm
              - text: íŒŒì´ì¬
                url: /category/python
              - text: ìë°”
                url: /category/java
              - text: <br>
              - text: WEBê°œë°œ
                url: /category/web
              - text: DRUPAL
                url: /category/drupal
              - text: <br>
              - text: ë¬¼ë¦¬í•™
                url: /category/physics
              - text: <br>
              - text: ë„ì ë„ì 
                url: /category/diary
                
    - text: About Me
      url: /about/
#     - text: My Projects
#       url: /projects/

url: ""
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']

# Math equation
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
